parameters:     
  - name: action
    type: string
  - name: tfPool
    type: string
  - name: stageName
    type: string
  - name: dependsOn
    type: object
    default: {}
  - name: adoEnvironment
    type: string
  - name: pluginCacheDir
    type: string
  - name: terraformVersion
    type: string
    default: 1.14.4

    
stages: 
  - stage: '${{ parameters.stageName }}'
    ${{ if eq(parameters.action, 'create') }}:
        displayName: '${{ parameters.stageName }} - Plan Create'
    ${{ if eq(parameters.action, 'destroy') }}:
        displayName: '${{ parameters.stageName }} - Plan Destroy'
    ${{ if eq(parameters.action, 'rotate') }}:
        displayName: '${{ parameters.stageName }} - Plan Rotate'
    ${{ if eq(parameters.action, 'none') }}:
        displayName: '${{ parameters.stageName }} - Plan None'
    dependsOn:
      - 'init'
      - ${{ each dep in parameters.dependsOn }}:
        - ${{ dep }}
    jobs:
      - deployment: '${{ parameters.stageName }}'
        ${{ if eq(parameters.action, 'create') }}:
          displayName: '${{ parameters.stageName }} - Plan Create'
        ${{ if eq(parameters.action, 'destroy') }}:
          displayName: '${{ parameters.stageName }} - Plan Destroy'
        ${{ if eq(parameters.action, 'rotate') }}:
          displayName: '${{ parameters.stageName }} - Plan Rotate'
        ${{ if eq(parameters.action, 'none') }}:
          displayName: '${{ parameters.stageName }} - Plan None'
        environment: '${{ parameters.adoEnvironment }}'
        pool:
          name: ${{ parameters.tfPool }}
        condition: succeeded()
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  # Load secrets
                  ## TODO
                - task: DownloadPipelineArtifact@2
                  displayName: Pull terraform artifact
                  inputs:
                    source: current
                    path: $(Agent.ToolsDirectory)/terraform/
                    artifact: terraform

                - task: DownloadPipelineArtifact@2
                  displayName: Pull terraform plugin cache artifact
                  inputs:
                    source: current
                    path: ${{ parameters.pluginCacheDir }}
                    artifact: terraform_plugins

                # Output build info
                - task: Bash@3
                  displayName: Release information
                  inputs:
                    targetType: 'inline'
                    failOnStderr: true
                    workingDirectory: $(Agent.BuildDirectory)
                    script: |
                      echo "envClass: @@@@@@@@@@"
                # Install terraform version for a component (should be taken from tools cache)
                - task: TerraformInstaller@0
                  displayName: Installing Terraform ${{ parameters.terraformVersion }}
                  inputs:
                    terraformVersion: ${{ parameters.terraformVersion }}

                  # Set terraform providers permissions
                - task: Bash@3
                  displayName: Set terraform providers permissions
                  inputs:
                    targetType: 'inline'
                    failOnStderr: true
                    workingDirectory: $(Agent.BuildDirectory)
                    script: |
                      chmod -R 755 ${pluginCacheDir}/
                  env:
                    pluginCacheDir: ${{ parameters.pluginCacheDir }}

                # Run terraform init
                - task: Bash@3
                  displayName: Run Terraform Init 
                  inputs:
                    targetType: 'inline'
                    failOnStderr: true
                    workingDirectory: $(Build.SourcesDirectory)
                    script: |
                     pwd
                     ls
                     terraform init \
                     -reconfigure \
                     -input=false \
                     -backend=${TF_BACKEND_ENABLED} \
                  env:
                    TF_BACKEND_ENABLED: false
          
